### ISSUE TITLE
NPM Package please

### ISSUE THREAD

**Issue by MartinMuzatko** [photopea/UPNG.js#1]

**Comment by photopea** [comment]
What is NPM? Do you think you can do that?

**Comment by photopea** [comment]
It seems like I have to download and install some special software, to publish UPNG.js in "npm".  When I update my library, will I have to update it both at GitHub and npm, or npm can somehow connect to GitHub and download the latest version?

**Comment by MartinMuzatko** [comment]
Hello! I'm sorry, I didn't know you were unaware of NodeJS/NPM. NPM is the largest package management solution on earth. Which enables other developers to download and use your code more easily.
Which means: install via console commands (`npm install upng`)
and usage via `require('upng')` for example. Also, you want to avoid that you are littering the global object namespace (`window.upng`)).

I'll see if I can find the time to create a pull request to publish it to NPM, however you should be the one publishing to NPM, since you created the library.  Documentation can be found here: https://docs.npmjs.com/cli/publish

Creating the package to make it available for NPM is pretty trivial.

**Comment by photopea** [comment]
Do they have a web interface? I use GitHub through the web interface. It seems crazy to me to download an install some software just to send 12 kB to some server.

**Comment by erykpiast** [comment]
No, they don't. You need to install special this package manager software ([npm](https://www.npmjs.com/package/npm)), which runs on and is shipped with its own virtual machine ([node.js](https://nodejs.org/en/)). The latter one is [often used](https://www.quora.com/What-are-the-biggest-websites-built-with-Node-js-on-the-server-side/answer/Ga%C3%ABtan-Voyer-Perrault) as a web server, [platform for running desktop applications](https://electron.atom.io/) or even for [controlling physical devices](https://cylonjs.com/) via Arduino or Raspberry Pi.

I can see you use "global export" pattern in your code, which is not recommended anymore. You need at least [CommonJS](https://nodejs.org/docs/latest/api/modules.html) module, better - [UMD](https://github.com/umdjs/umd) or ideally [ES6 module](http://2ality.com/2014/09/es6-modules-final.html) transpiled to UMD by some bundler, like [Webpack](https://webpack.js.org/), [Brunch](http://brunch.io/) or [Rollup](https://rollupjs.org/) (there are a lot of more of these).

To make code readable and admired by everybody you should use the latest features of EcmaScript language and then [transpile](https://scotch.io/tutorials/javascript-transpilers-what-they-are-why-we-need-them) it to ES5, probably with [Babel](https://babeljs.io/).

As the thing you build is a library, you may want to use [TypeScript](https://www.typescriptlang.org/), which is basically superset of EcmaScript, providing type signatures and compile-time type-checks (TypeScript is compiled to JavaScript, either ES5 or ES6, so you may or may not use Babel along with that). Even people not writing TypeScript would still benefit from it as modern editors like [VSCode](https://code.visualstudio.com/) are able to show type hints based on TypeScript types.

Separate topic is Test-Driven Development. I can see you didn't write any test for your code, which is no more acceptable in open source community. Make sure to choose some test runner like [Mocha](http://mochajs.org/), [Jasmine](https://jasmine.github.io/) or [Ava](https://github.com/avajs/ava) along with one of assertion libraries: [Chai](http://chaijs.com/), [PowerAssert](https://github.com/power-assert-js/power-assert) or maybe [built-in `assert` function](https://nodejs.org/api/assert.html) from node.js as you already have it installed. Ideally before each deploy you would run tests cross-browser on [BrowserStack](browserstack.com) or [SauceLabs](https://saucelabs.com/) through [Karma](https://karma-runner.github.io/1.0/index.html), to make sure your code works everywhere.

If you use Continuous Integration server for all that transpilation, building and testing stuff, you will be able to add [fancy badges](https://docs.travis-ci.com/user/status-images/) to README in your GitHub repository or [GitHub Pages](https://pages.github.com/).

That's only tip of the iceberg. Welcome to front-end development A.D. 2017.

PS
You can also ignore all of this and just continue doing awesome work as you were doing so far!

**Comment by photopea** [comment]
Thank you very much for your comments. It seems like downloading, installing and learning how to use all these programs would take me more time, than I spent developing UPNG.js . I don't need them for any other purpose. Thus, I decided to leave that task to somebody else (feel free to publish UPNG.js on npm or any other "code databases" / websites).

PS  I still think, than when imagining a "standard javascript environment", you should not imagine Node.js (which thousands of people have) but a web browser (which billions of people have).
