### ISSUE TITLE
Request for a release tag

### ISSUE THREAD

**Issue by Billy4195** [photopea/UPNG.js#14]
Hi @photopea ,
We are [cdnjs](https://github.com/cdnjs/cdnjs), we're going to host this library.
And our git auto-updater in [cdnjs](https://github.com/cdnjs/cdnjs) need tags to recognize versions and update it.
Would you like to add tags for this repo?

If you have any suggestions, please let me know.
Thank you.

[cdnjs/cdnjs#12257](https://github.com/cdnjs/cdnjs/issues/12257)

**Comment by photopea** [comment]
Hi Billy, what are those tags?  There may be hundreds of services, who would want to host our library, and it sounds crazy to adapt our content for each of these services.

Can you detect the update by other GitHub parameters? E.g. you can parse it out from the HTML code of our repository page.

**Comment by Billy4195** [comment]
@photopea Because we found that your repo has some popularity on GitHub, it means there exists some people using your code, and CDNJS is just a platform to provide your code on our website for others to use, but if the users want new features, they should open issue on your repo and discuss with you.
Our auto-updater can automatically grab the tags info on GitHub repo. 

The tags can be added by using [`git tag -a`](https://git-scm.com/book/en/v2/Git-Basics-Tagging) then push on GitHub or just [add release](https://help.github.com/articles/creating-releases/) on GitHub page.

**Comment by photopea** [comment]
I am new to Git and Github. I upload everything here through the web interface.
What tags exactly do you need? Will I have to change tags every time I upload a new version?

**Comment by Billy4195** [comment]
@photopea Oh, I found that you had release this package on npm, right?
Our auto-updater can also use npm package to update files, that means you no need to add release tags on GitHub, we can use the source code on [npm](https://www.npmjs.com/package/upng-js)

If you want to add release tag on GitHub, as well, then you can refer to these two website: [`git tag -a`](https://git-scm.com/book/en/v2/Git-Basics-Tagging) and [`add release`](https://help.github.com/articles/creating-releases/)

**Comment by photopea** [comment]
One of our fans "copies" the latest version to NPM. There is an old version on NPM right now. @Scimonster  can you help us here?

**Comment by Scimonster** [comment]
OK, updated the version on NPM.
@photopea Can you ping me when you push a code update so i can update NPM?

**Comment by photopea** [comment]
@Scimonster  ok, I will "mention" you when I update UPNG next time.
