### ISSUE TITLE
node.js buffer 

### ISSUE THREAD

**Issue by xiaomaisu** [photopea/UPNG.js#15]
If I want to use UPNG.decode(buffer) in node.js,can I use the following writing?

`fs.readFile(file.path, function(err, stat) {
       const buffer = UPNG.decode(stat)
}`

can I deliver node.js buffer to the method? If I can't, how should I do it in node.js?

**Comment by photopea** [comment]
Hi, I am not familiar with node.js . If the "stat" variable is an ArrayBuffer with a PNG image, you can do it.

**Comment by Scimonster** [comment]
You first need to [convert the Node buffer to an ArrayBuffer](https://stackoverflow.com/a/12101012/3187556).
