### ISSUE TITLE
Calling UPNG.encode with fractions for width and height causes an issue

### ISSUE THREAD

**Issue by friksa** [photopea/UPNG.js#18]
This is probably something that should only be documented.

We are scaling images and the calculated width and heights are fractions.  When passing these fractions to UPNG.encode, the resulting image is broken and only contains a few lines.  The fix is to round the width and height the whole numbers.  This could be done in the UPNG library or documented in the API call.

Thanks for a great library!

**Comment by photopea** [comment]
Do you also give half-pixels (color data) to UPNG.encode() ? How does it look like?

**Comment by photopea** [comment]
I think it is obvious, that width and height (in pixels) have to be positive integers. The conversion from non-positive integers (e.g. from Strings, or decimal numbers, as in your case), should be done outside UPNG.js

**Comment by friksa** [comment]
Sounds good.

**Comment by AutumnWhj** [comment]
@friksa hey , can you tell me how to fix this bug ?  i have the image(the original size is 100x100), i want to compress to 40* 40, but it not working, like this result
![image](https://github.com/user-attachments/assets/94f4aab6-7a0a-4db2-9623-596208e9949f)

**Comment by photopea** [comment]
You can use Canvas - context2d to do it for you. Use Context.drawImage(....) and then, read back the new RGBA data.

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage
