### ISSUE TITLE
Running into issue with cnum=0 and image with less than 256 colors

### ISSUE THREAD

**Issue by martin19** [photopea/UPNG.js#20]
Thanks for your compressor, it works very well.

https://github.com/photopea/UPNG.js/blob/5e5af183a3dda1e320b90a1830b3f64bc92010d4/UPNG.js#L511

should it say `var img32 = new Uint32Array(bufs[j].buffer)` in this line?

**Comment by photopea** [comment]
No, since "bufs" has to be an array of ArrayBuffers (i.e. not Uint8Array or Uint32Array). It will probably work with ArrayBufferViews, too, but it would be slower and use more RAM.
