### ISSUE TITLE
Encoding returns empty image

### ISSUE THREAD

**Issue by zakjan** [photopea/UPNG.js#22]
Decoding TIFF file G31D.TIF from [TIFF samples](https://www.fileformat.info/format/tiff/sample/index.htm) and encoding it with UPNG returns empty image.

```
        // read TIFF
        const ifds = UTIF.decode(tiffBuffer);
        UTIF.decodeImages(tiffBuffer, ifds);
        const page = ifds[0];
        const rgba = UTIF.toRGBA8(page);

        // write PNG
        const pngBuffer = UPNG.encode([rgba], page.width, page.height);
```

I was able to fix it using undocumented param for UPNG.encode forbidPlte=true, but it is about two times slower than [pngjs](https://github.com/lukeapage/pngjs).

**Comment by photopea** [comment]
Hi, I just updated UPNG.js, can you try it with a new one?

btw. "Frames" for UPNG are ArrayBuffers, while UTIF.toRGBA8 returns Uint8Array. You should use 

    UPNG.encode([rgba.buffer], ...

**Comment by zakjan** [comment]
Thanks a lot, my bad, `rgba.buffer` did the trick

**Comment by photopea** [comment]
I am sorry for not using consistent types with UTIF and UPNG :D
