### ISSUE TITLE
PNG Encoding sometimes fails

### ISSUE THREAD

**Issue by friksa** [photopea/UPNG.js#24]
PNG encoding sometimes fails... This is an example that frequently fails:
var bin = UPNG.encode([newData.data], w, h, 0);

Using 256 colors instead of 0 (unlimited) mostly works, but not always.

This is an example that failed with 0 (unlimited colors) - resulting PNG at:
https://x1.gatherworks.com:443/doc/572BD2A2CCA63DBA5EB3C21DE115908B/ffa002be102547399238a7af4a8b3e6f.png

Attaching a screen shot of the application window that was PNG encoded.
![2018-04-03_04-12-30](https://user-images.githubusercontent.com/2990564/38237448-3ec57c1e-36f5-11e8-8393-107b200579cc.png)

I am not sure what the best way is to give you a recreatable example since it depends on the contents of the buffer... but it frequently happens when using 0 (unlimited colors).  Encoding mostly works when using this instead (but not always):
var bin = UPNG.encode([newData.data], w, h, 0, null, true);

**Comment by photopea** [comment]
Hi, can you try to send an ArrayBuffer as a frame? That would be newData.data.buffer in your case.

**Comment by friksa** [comment]
This buffer is 160x46
[buffer.zip](https://github.com/photopea/UPNG.js/files/1871026/buffer.zip)

**Comment by photopea** [comment]
Did you try to give it an ArrayBuffer instead of ArrayBufferView?

**Comment by friksa** [comment]
Not sure I understand the question.  This is how I get the buffer.
var newData = context.getImageData(0, 0, w, h);

**Comment by photopea** [comment]
Then, you need to call

    var bin = UPNG.encode([newData.data.buffer], w, h, 0, null, true);

**Comment by friksa** [comment]
You called it.  After testing, it seems that was the issue.  Curious that it worked pretty well most of the time for non 0 color values.

It might help others too by documenting how to take content from a canvas and encode it to PNG using this library.

Thanks again for a great library!!

**Comment by photopea** [comment]
Ok thank you for the donation! btw. you are the first person to donate to UPNG.js :)
