### ISSUE TITLE
cnum parameter = 0 produces grey image

### ISSUE THREAD

**Issue by luastoned** [photopea/UPNG.js#27]
Not quite sure why this happens, but when I use

`upng.encode([rawBuffer], imageWidth, imageHeight, 0);`

it results a grey image.

**Comment by photopea** [comment]
Hi, could you tell us, what your "rawBuffer" is? Maybe you have a gray image in it (R=G=B).

What do you mean by "data points"?

**Comment by luastoned** [comment]
rawBuffer is a regular colored image generated from rasterdata.

When I change cnum to 10 or 100 it produces the desired image, there are approx ~40 different colors in the image.

`const png = upng.decode(imageBuffer); // png.length = 272`

I'm rather confused because both width and height are 16, eg. it should be 256?

**Comment by photopea** [comment]
cnum > 0  is for compressing PNG images. cnum = 0 should preserve original colors. If you show us your buffer or image somehow, I can investigate it.

png.data contains the raw image data. You should read the PNG spec to understand what is inside. We recommend using UPNG.toRGBA8() to get 8-bit RGBA data (would give you 16 x 16 x 4 bytes).

**Comment by photopea** [comment]
I guess I can close it now.

**Comment by luastoned** [comment]
I feel really dumb, apparently `upng` on npm is not `upng-js`.

Case closed, I did not encounter any of the above with the proper lib.
