### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by EmpireWorld** [photopea/UPNG.js#3]
Hi.

please publish this package to NPM.

Thanks.

**Comment by photopea** [comment]
I don't like using command-line programs (I published UPNG.js here through the web interface). Can you publish it on NPM?

**Comment by EmpireWorld** [comment]
If you are a JavaScript should know Node.js and using NPM.

Also there is no mandatory to make your app an command-line program, it is just a way of working with your package.

I will add npm package in my spare time.

Thanks.
