### ISSUE TITLE
CLI support

### ISSUE THREAD

**Issue by landsman** [photopea/UPNG.js#35]
Missing for me CLI API for using with nodejs as microservice in Docker for example. Can be written as [script](https://docs.npmjs.com/misc/scripts) in package.json.

**Comment by Scimonster** [comment]
Feel free to submit a pull request. I kind of doubt @photopea will do this,
as they don't really use Node.

**Comment by photopea** [comment]
I have no experience with Node.js :( just tell me what you want me to add into package.json and I will add it.

**Comment by Scimonster** [comment]
It's more complicated than just adding a line to package.json. A script to
handle command line arguments and output needs to be written.

**Comment by landsman** [comment]
Yeah, there must be some nodejs wrapper for it.

**Comment by photopea** [comment]
Guys, I will close it. I can not provide a special update everytime somebody invents their own javascript processing tool :(

**Comment by landsman** [comment]
NodeJS is pretty much standard tool today. It can be automatically billed via Github Actions and published at packagist, where most of developers searching libs in these days.

**Comment by fisker** [comment]
I use upng with imagemin https://www.npmjs.com/package/imagemin-upng , and imagemin has cli

```sh
imagemin --plugin=upng foo.png
```
