### ISSUE TITLE
Cannot create a .png from UPNG.encode()

### ISSUE THREAD

**Issue by yussefsoudan** [photopea/UPNG.js#38]
I'm currently trying to retrieve a .tiff image from desk, converting it to a .png and writing the .png to a file on desk.

The following code produces a .png that when I try to open it produces the following error, 'It may be damaged or use a file format that Preview doesn’t recognise.'

```
let fs = require('fs');
let UTIF = require('utif');
let UPNG = require('upng-js');

let contents = fs.readFileSync('img.tiff');
let ifd = UTIF.decode(contents);
let height = ifd[0].t270['REAL_HEIGHT'];
let width = ifd[0].t270['REAL_LENGTH'];

UTIF.decodeImage(contents, ifd[0]);
let rgba = UTIF.toRGBA8(ifd[0]);
let png = UPNG.encode([rgba], width, height);


 fs.writeFile('f.png',  Buffer.from(png), (err) => {
    if (err) throw err;
    console.log('It\'s saved!');
});
```

**Comment by photopea** [comment]
Hi, what is the "require" function? Do you see any errors while running your JS code?

Is the value of width/height what you expect? I think you should access ifd[0].width and ifd[0].height.

The size of "rgba" (in bytes)  should be width*height*4. Is it true?

**Comment by yussefsoudan** [comment]
Thanks for your response! 
I've just console.log()ed the height and width; they both are undefined. 
I just adjusted to ifd[0].width and ifd[0].height, but they both also are undefined.

Given that, I console.log()ed ifd, and this is the result:

```
{ t254: [ 0 ],
    t256: [ 1653 ],
    t257: [ 620 ],
    t258: [ 1 ],
    t259: [ 8 ],
    t262: [ 1 ],
    t266: [ 1 ],
    t270: [ 'NCR,PARMS=2,REAL_HEIGHT=620,REAL_LENGTH=1653' ],
    t273: [ 327 ],
    t274: [ 1 ],
    t277: [ 1 ],
    t278: [ 620 ],
    t279: [ 16196 ],
    t280: [ 0 ],
    t281: [ 1 ],
    t282: [ 200 ],
    t283: [ 200 ],
    t284: [ 1 ],
    t293: [ 0 ],
    t296: [ 2 ],
    t317: [ 1 ] } ]
```

Would there be a sensible, concise way of accessing the height and width?

**Comment by yussefsoudan** [comment]
I should also note, than when I entered the width (length) and height manually, the image produced was empty. Any ideas as to why this is the case?

**Comment by photopea** [comment]
Try to use UTIF according to the documentation

     var ifds = UTIF.decode(arrayBuffer);
     UTIF.decodeImage(arrayBuffer, ifds[0])
     var rgba  = UTIF.toRGBA8(ifds[0]);  // Uint8Array with RGBA pixels
     console.log(ifds[0].width, ifds[0].height, ifds[0]);

Let me know if you see the correct result.

**Comment by yussefsoudan** [comment]
Thanks again for keeping up with me!

This worked, and the width and height are now defined. I'm currently just trying to resolve the 2nd part of the problem, which's to save that to a file as a .png.

```
let arrayBuffer = fs.readFileSync('img.tiff');

let ifds = UTIF.decode(arrayBuffer);
UTIF.decodeImage(arrayBuffer, ifds[0])
var rgba  = UTIF.toRGBA8(ifds[0]);

let png = UPNG.encode([rgba], ifds[0].width, ifds[0].height);
console.log(png);

```

console logging 'png' means results in 'ArrayBuffer { byteLength: 249 }'. Any ideas what I could do to make the conversion to .png? Or if that is even possible?

**Comment by yussefsoudan** [comment]
Actually, I forgot to read there was a 4th argument to UPNG.encode(), it now works.
Thanks so much for keeping up with me!

**Comment by photopea** [comment]
UPNG.encode() should work without a fourth argument.
