### ISSUE TITLE
Feature request: NPM module

### ISSUE THREAD

**Issue by mn4367** [photopea/UPNG.js#4]
Could you create an NPM module of UPNG.js? Samples on how to use it in a Node.js or browser context would also be very helpful.

**Comment by landsman** [comment]
We was talk about this with author today.
I hope that npm module will be created soon.

**Comment by photopea** [comment]
I asked them to make a web interface for making NPM packages: https://github.com/npm/npm/issues/16625

BWT. I think that GitHub should create its own alternative to NPM, since a lot of interesting software is already here and GIT protocol seems to be uncomfortable for that.

**Comment by backspaces** [comment]
I'm sympathetic with the npm package request, but honestly, for a project this young, lets:
- Agree that it's time for npm & github to collaborate
- Be content with rawgit for a while: https://rawgit.com/photopea/UPNG.js/master/UPNG.js

Npm is attempting to integrate with github and I use it for one of my dependencies. See:
https://docs.npmjs.com/cli/install
.. and search for github.

The code is delightfully clean (too bad pako isn't, alas). My wish is coming in the next issue :)

**Comment by awerlang** [comment]
Also, to be usable in a Node environment, the file needs this change on the top:

```js
import pako from 'pako';
export var UPNG = {};
```

**Comment by landsman** [comment]
Some progress guys? :-)

**Comment by mn4367** [comment]
I'm already using UPNG.js in a node module style for [this module](https://www.npmjs.com/package/png2icons). If @photopea is OK with it, I can try to publish a pure UPNG.js module. But I can't guarantee any time frame although it shouldn't take too long.

**Comment by Scimonster** [comment]
@awerlang Actually you shouldn't use ES6 module syntax yet, as it is not supported by NodeJS. Use

```
var pako = require('pako');
module.exports = {};
```

**Comment by awerlang** [comment]
@Scimonster you're right, I should have mentioned this requires a transpiler

**Comment by Scimonster** [comment]
It looks like someone did publish this to NPM. https://www.npmjs.com/package/upng

Unfortunately without attribution to the original author.

**Comment by landsman** [comment]
Sad! @photopea !

**Comment by mn4367** [comment]
Yes, and also without a public repository and a bunch of IntelliJ IDEA config stuff which shouldn't be part of an NPM module.

**Comment by photopea** [comment]
@Scimonster  would you please be able to get UPNG.js to npm, too?

**Comment by mn4367** [comment]
> @Scimonster would you please be able to get UPNG.js to npm, too?

Should @Scimonster do it or should I do it.

**Comment by Scimonster** [comment]
@photopea Yes, with the same collaborator agreement we had on UTIF.

**Comment by photopea** [comment]
Ok, I made you a collaborator. Please keep UPNG.js usable in a browser as it is. Add a mention about NPM into README.md . Thank yo very much. I really appreciate your help :)

**Comment by Scimonster** [comment]
Done. I had to upload as `upng-js` because as i said above, someone already took `upng`.
