### ISSUE TITLE
pako is not defined

### ISSUE THREAD

**Issue by 55utah** [photopea/UPNG.js#41]
use method 'UPNG.encode' get error:
"pako is not defined"
in UPNG.js line 789.
![image](https://user-images.githubusercontent.com/17704150/69206533-e6451900-0b87-11ea-9e26-4795732b9955.png)

**Comment by 55utah** [comment]
sorry, I find the reason. 
fix it by using pako.js.

**Comment by dbarzin** [comment]
Problem still present in current version : ReferenceError: pako is not definedUPNG.js:790:14

**Comment by photopea** [comment]
UPNG.js requires pako.js , as described in the README file.

**Comment by dbarzin** [comment]
Thanks, pako.js from https://github.com/nodeca/pako/blob/master/dist/pako.js has to be included before.

**Comment by photopea** [comment]
yes, it is mentioned in Readme.
