### ISSUE TITLE
use Rec. 709 component coefficients for color distance

### ISSUE THREAD

**Issue by leeoniya** [photopea/UPNG.js#42]
hey @photopea 

i ran some visual tests and it seems that using the coefficients yields a noticeable improvement in quality across a diverse set of images. for now, i only tested at the default 255 colors setting of http://upng.photopea.com/

```js
UPNG.quantize.dist = function(q,   r,g,b,a) {  var d0=r-q[0], d1=g-q[1], d2=b-q[2], d3=a-q[3];  return d0*d0*.2126+d1*d1*.7152+d2*d2*.0722+d3*d3;  }
```

the coeffs could probably be re-scaled to avoid one of the mults.

- gradients have smoother, more pleasant transitions
- color shifting is reduced
- slight increase in resulting filesize.
- perf seemed unchanged or even slightly improved.

i tested for all the images here: https://github.com/leeoniya/RgbQuant.js/tree/master/demo/img

plus these:

![pixel3](https://user-images.githubusercontent.com/43234/72001399-051c6f00-320b-11ea-93f0-709725f64267.png)
![nightshot](https://user-images.githubusercontent.com/43234/72001400-051c6f00-320b-11ea-8c8d-c081087bdb6d.png)
![artificial](https://user-images.githubusercontent.com/43234/72001401-051c6f00-320b-11ea-86fc-4eba3527199d.png)

**Comment by photopea** [comment]
Hi, thats interesting. Could you maybe show me specific images, side by side, when the better quality is the most visible?

**Comment by leeoniya** [comment]
it's easier to see the differences by cycling between the 3 versions of each image orig -> weighted -> unweighted. side-by-side will be harder to evaluate. in some cases the improvement is obvious (gradients) without the original, but for slight color shifting comparisons you need all 3 overlayed.

i can prepare all 3 sets for you if you'd like later today.

**Comment by photopea** [comment]
Yes, please, send me an archive with several such images.

**Comment by leeoniya** [comment]
like #43, you'll probably assert that UPNG's results are better.
