### ISSUE TITLE
Issues with quant and 256 colors

### ISSUE THREAD

**Issue by alpfactory-alex** [photopea/UPNG.js#48]
Your library works really good however the quanitizer seems to have an issue I could really not figure why. See this sample gif image which contains exactly 256 colors:

![gif-input](https://user-images.githubusercontent.com/19890104/79852837-7f8e8a80-83c7-11ea-9892-0f7d90fe601f.gif)

Trying to compress this with UPNG into a palette of 256 colors actually produces 252 colors palette only and seems to have some white gaps ? along the line:

![gif-output](https://user-images.githubusercontent.com/19890104/79852908-9b922c00-83c7-11ea-9114-f1f276146383.gif)

Also around yellow you can see its not perfect. Doing the same but giving the compress palette of zero so he manually gets all colors produces the exact 256 colors and also gives a better optical result:

![gif-output](https://user-images.githubusercontent.com/19890104/79852991-bfee0880-83c7-11ea-8344-a6f51dd36784.gif)

any idea? @photopea I assume you might know how to improve especially the white artifact issue?

**Comment by photopea** [comment]
Hi, are you using the latest UPNG.js from here? There are some old versions on npm, we do not maintain it.

What parameters did you use to make your PNGs? I can not reproduce it.

**Comment by alpfactory-alex** [comment]
Yes I am using the latest version from here. I am using this code to call UPNG for this GIF:

```
const compressedFrames = UPNG.compress(
        scene.frames.map(frame => frame.getImageBuffer()),
        scene.width,
        scene.height,
        256,
        [true, false, false, 0, false]
    )
```

Also tried to set the onlyBlend to false (I set it to true to make it work correctly for transparent gif animations) but doesn't change a thing. Only if I set the ps to 0 so it doesn't quant it works correctly.

**Comment by photopea** [comment]
Oh, I did not notice you are converting GIF to GIF, not to PNG. Could it be an error in your GIF encoder?

The method UPNG.compress() is not described at our README. We recommend to use UPNG.encode() for encoding PNG, and UPNG.quantize() for quantization. But I guess you are using it the right way and the problem is in your GIF encoder.

**Comment by alpfactory-alex** [comment]
@photopea Yeah I am doing the GIF thing. I don't think so. As mentioned, the GIF image contains exactly 256 colors. Running it with your compress function providing max. 256 colors it runs quantize *but* results in 252 colors to be generated not 256. If I pass 0 in the compress function so it collects all colors for the palette it correctly results in 256 colors palette and the generated image is correct.

So the problem is not in the gif encoder its definitely in the quantize .. any idea why's that and it misses those 4 colors?

**Comment by photopea** [comment]
Oh, you are right, Photopea produces 252 colors. Actually, when you specify CNUM (number of colors), our quantizer looks for a palette with at most CNUM colors (not exactly CNUM). If your image had only two colors and you specified CNUM=5, it will not invent new colors for your image.

So currently, UPNG works this way:
if CNUM==0  : use real colors, palette if possible
else :  Quantize, can get less than CNUM colors

I can make it count the number of colors in advance and do not quantize, if the total number of colors is <= CNUM . But counting the colors can make UPNG much slower (as there can be millions of colors).

**Comment by photopea** [comment]
But I still think the white gap in your GIF is because of GIF encoder.

**Comment by alpfactory-alex** [comment]
I think it should definitely first count to approx. the given number of colors and stop if it goes beyond so it prevents the case of million colors. But it makes no sense to run the quant if the image (like my sample) contains less or equal colors as the palette. As such a palette will then be much better quality. Could you change that? I could change it locally but makes no sense to get our of synch with your lib.

I think the issue is definitely the quant. Painting the returned indexed buffer issues the same result as it is exported to GIF then. Its simply missing those four colors and matches them wrongly not sure why.

**Comment by alpfactory-alex** [comment]
Furthermore I understand the quant *may* result in less colors as I give it if there *are* less colors but the given image has exactly those 256 colors so why does it miss four colors.

**Comment by alpfactory-alex** [comment]
@photopea tried to find my way around in the quant but have to admit I am pretty lost where to start.. any idea? ;(

**Comment by alpfactory-alex** [comment]
I tried in your photopea editor (btw REALLY cool) and it seems the result is similiar to mine but doesn't have the artifacts. Though I get them on rendering too. Is there maybe a newer version of UPNG available? 

Also I tried your UDOC pretty cool as well but it seems the PDFs I try to render are working better in photopea than in the UDOC version you have out there. Is there also maybe a newer version available?

**Comment by photopea** [comment]
Actually, there was an error in a quantizer, when computing an eigenvector and an eigenvalue of a matrix. I fixed it and it finds all 256 colors now. Please, update your UPNG.js file from here.

I update UDOC.js very often. The version here on GitHub is quite old. I did not update it, as I felt like nobody is using it. But Photopea.com always uses the latest version.

**Comment by alpfactory-alex** [comment]
@photopea Cool thanks alot. Could you update UDOC? We'd actually love to provide code and fixes to your codes as well but it seems you always develop locally so your code goes out of synch with github? Maybe could be improved so others can help working on it?

**Comment by friksa** [comment]
I think you will be surprised how many people are using this library.  It is the best open source version we could find.  Because it does not have a proper npm install process, you don't get accurate usage counts.  Thank you for a great lib!

**Comment by alpfactory-alex** [comment]
Yeah your libs should really (if you would want to) be developed on github including proper npm releases and also proper support for CommonJS / ES modules so it could be used more widely without modifications. It seems you are using your modules globally but that could still be done in a proper build process...
