### ISSUE TITLE
Is there  async method?

### ISSUE THREAD

**Issue by 415848878** [photopea/UPNG.js#50]

**Comment by photopea** [comment]
What do you mean? You should be able to use the current library from any place of your code.

**Comment by 415848878** [comment]
I use upng on a game engine. I convert RGBA to png arraybuffer and save it as a file. The conversion process takes about 2 or 3 seconds. I don't want to jam the main thread. Is there any async method

**Comment by photopea** [comment]
What kind of data do you store inside PNG images? If you have game screenshots, use JPG for them (the encoding would take 100ms and files are 5x smaller). We also have a method for producing valid PNGs without any compression (takes 10ms for any image, but the output size is always 4 Bytes per pixel), but it is not exposed in our API now.

To avoid using the main thread, you could call UPNG.js in a web worker.

**Comment by 415848878** [comment]
I make mobile games without web worker, which can only be used in the main thread and requires PNG pictures,

**Comment by photopea** [comment]
I think it is not possible to make Javascript run outside the main thread without a web worker.

**Comment by 415848878** [comment]
Yes, but it can be executed in frames. This is a common strategy to prevent the game from jamming. The proportion setTimeout can skip to the next frame to continue execution. For example, if one frame is 16ms, you can skip to the next frame after 8ms.

**Comment by photopea** [comment]
We do not have an option to pause the PNG encoding, and to do it in multiple steps :(

**Comment by photopea** [comment]
You probably mean the CPU executing multiple threads on a single CPU core. But that is what Web Workers are for.

**Comment by 415848878** [comment]
OK, thank you for your answer. At present, it can only be used like this. Thank you for your work.
