### ISSUE TITLE
New package version

### ISSUE THREAD

**Issue by netahe** [photopea/UPNG.js#51]
Hey,

Would you consider publishing an up-to-date version of this package to npm? The latest version is 3 years old, and doesn't reflect the current state of the project.

**Comment by photopea** [comment]
Hi, I am not an NPM user and I don't know what should I download / install to do it. Is it possible through a web browser?

Could you put UPNG.js to NPM?

**Comment by netahe** [comment]
Hey,

First of all, UPNG is already on npm registry, [here](https://www.npmjs.com/package/upng-js).  I can't make changes to it, because I'm not registered as an owner/maintainer of the package. The package was originally published by, @Scimonster, maybe they can help?

**Comment by photopea** [comment]
I asked @Scimonster to update it in February, but he did not reply: https://github.com/photopea/UPNG.js/issues/44

As I see, UPNG.js is on NPM eleven times: https://www.npmjs.com/search?q=upng So if you add one more copy, it should be fine.

**Comment by Richienb** [comment]
@photopea To release a new update, download the repository and increment the version in the package.json. Then, with [Node.js](https://nodejs.dev/) installed, run `npm publish`. Alternatively, I can help with the publishing if you add me as a collaborator and run `npm owner add upng-js richienb` to give me publish perms.

**Comment by photopea** [comment]
Please, if you need an npm version, put it on npm yourself. I do not use npm or Node.js .
