### ISSUE TITLE
making an official release

### ISSUE THREAD

**Issue by mortac8** [photopea/UPNG.js#55]
We would very much like to use UPNG in one of our projects.  However we can't officially use any FOSS code that isn't versioned with a release.  Is there some way I can help in creating a release for the current UPNG.js?

**Comment by photopea** [comment]
Hi, what do you mean by creating a release? I call it a release when I publish it here on GitHub.

**Comment by mortac8** [comment]
Like a GitHub release https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository#creating-a-release

Just something to tag with version 1.0 or whatever so we can properly document the product we're using.

**Comment by photopea** [comment]
I published a release, is it ok now?

**Comment by mortac8** [comment]
Yes.  Thank you so much!
