### ISSUE TITLE
how scale image from rgba

### ISSUE THREAD

**Issue by 415848878** [photopea/UPNG.js#56]

**Comment by photopea** [comment]
Hi, what do you mean?

**Comment by 415848878** [comment]
i have rgba data  width * height   = 1000 * 1000, I want encode data to width* height = 500 * 500 。

**Comment by 415848878** [comment]
how write the code

**Comment by photopea** [comment]
I think there are many ways to do it. You can copy-paste pixels, but take only the pixel number 1, 3, 5, 7, 9...
Also, after each line of pixels, skip one line (i.e. use only lines 1, 3, 5, 7, 9 ...).

You can use a for loop or something. Such image transformations are out of the scope of this library.

**Comment by 415848878** [comment]
ok ,thank you

**Comment by AutumnWhj** [comment]
@415848878 hey so how to write the code, can tell me ?
i have upload file data width * height = 1000 * 1000, I want encode data to width* height = 500 * 500 。
