### ISSUE TITLE
Incorrect data length returned by UPNG.decode

### ISSUE THREAD

**Issue by oeway** [photopea/UPNG.js#58]
When calling UPNG.decode, it returns an imageObject. However, it seems the length doesn't correspond to `height*width*channels*bytesPerChannel`.

For example, I have an image 512x512x3 8-bit RGB image, the expected imgObj.data should have 786,432 length, however, the one I got is 786,944 (with a tail of 512 bytes).

**Comment by photopea** [comment]
Yes, that is on purpose. There is always extra H bytes (H is the height of the image in pixels). UPNG.js works better thanks to this.

We do not recommend to work with that "data" array. Use UPNG.toRGBA8() instead.
