### ISSUE TITLE
Incorrect decompression of iTXt compressed chunk

### ISSUE THREAD

**Issue by hbs** [photopea/UPNG.js#59]
The included image contains an iTXt chunk with compressed text. The text as included in the image is below (between ---8<---), but the text reported by UPNG.js is truncated.

---8<---
{"type":"MM","v":0,"lllat":37.82935664523393,"lllon":2.1654982957988977,"latstep":1.1820609867402251E-4,"lonstep":2.0685191139404875E-4,"lastbucket":1600439000999999,"bucketspan":43200.0,"bucketcount":2000,"gts":406,"positions":144622,"infos":[{"id":"???"},{"id":"227384750"},{"id":"377777000"},{"id":"247322400"},{"id":"1001"},{"id":"247235360"},{"id":"???"},{"id":"215185000"},{"id":"247013600"},{"id":"2470071"},{"id":"???"},{"id":"???"},{"id":"232010683"},{"id":"???"},{"id":"247325140"},{"id":"271000768"},{"id":"247138800"},{"id":"247374100"},{"id":"???"},{"id":"227655820"},{"id":"???"},{"id":"636015530"},{"id":"227776070"},{"id":"215959000"},{"id":"227830030"},{"id":"667001840"},{"id":"232022513"},{"id":"254276000"},{"id":"247415100"},{"id":"???"},{"id":"247362700"},{"id":"247211900"},{"id":"???"},{"id":"247373600"},{"id":"???"},{"id":"255912870"},{"id":"247329820"},{"id":"247067930"},{"id":"215595000"},{"id":"???"},{"id":"227886810"},{"id":"???"},{"id":"247621000"},{"id":"229490000"},{"id":"247178700"},{"id":"???"},{"id":"???"},{"id":"???"},{"id":"247279000"},{"id":"219024903"},{"id":"???"},{"id":"247229310"},{"id":"304214000"},{"id":"???"},{"id":"???"},{"id":"247214200"},{"id":"319068400"},{"id":"227126610"},{"id":"247327610"},{"id":"211670510"},{"id":"232019268"},{"id":"563096100"},{"id":"???"},{"id":"215426000"},{"id":"227208570"},{"id":"???"},{"id":"2288238"},{"id":"???"},{"id":"247130700"},{"id":"2470069"},{"id":"???"},{"id":"247219400"},{"id":"???"},{"id":"247278400"},{"id":"227779610"},{"id":"319096300"},{"id":"???"},{"id":"???"},{"id":"227184000"},{"id":"255806058"},{"id":"247208920"},{"id":"227665340"},{"id":"???"},{"id":"???"},{"id":"???"},{"id":"???"},{"id":"319053100"},{"id":"247086400"},{"id":"339446000"},{"id":"215121000"},{"id":"???"},{"id":"247121100"},{"id":"???"},{"id":"319025900"},{"id":"???"},{"id":"211411390"},{"id":"247036100"},{"id":"227060730"},{"id":"247149250"},{"id":"227986950"},{"id":"247370100"},{"id":"428042000"},{"id":"???"},{"id":"229953000"},{"id":"218024000"},{"id":"247372500"},{"id":"304416000"},{"id":"319064900"},{"id":"247150350"},{"id":"???"},{"id":"???"},{"id":"???"},{"id":"???"},{"id":"???"},{"id":"227873090"},{"id":"247106500"},{"id":"235011110"},{"id":"354298000"},{"id":"247391200"},{"id":"???"},{"id":"538001665"},{"id":"100265"},{"id":"111247103"},{"id":"247044300"},{"id":"319609000"},{"id":"269053000"},{"id":"2288237"},{"id":"247238500"},{"id":"205936130"},{"id":"???"},{"id":"319560000"},{"id":"227909190"},{"id":"???"},{"id":"215587000"},{"id":"247101800"},{"id":"???"},{"id":"228009700"},{"id":"???"},{"id":"374499000"},{"id":"672747000"},{"id":"247144800"},{"id":"227691460"},{"id":"247035390"},{"id":"235077715"},{"id":"247160170"},{"id":"247192100"},{"id":"247183200"},{"id":"538006592"},{"id":"378113355"},{"id":"247101100"},{"id":"354854000"},{"id":"605086020"},{"id":"???"},{"id":"226280000"},{"id":"215599000"},{"id":"227288820"},{"id":"???"},{"id":"247319800"},{"id":"211758910"},{"id":"378112621"},{"id":"247228600"},{"id":"248553000"},{"id":"227582180"},{"id":"227452730"},{"id":"255805606"},{"id":"???"},{"id":"???"},{"id":"235085866"},{"id":"228081000"},{"id":"247015400"},{"id":"636018142"},{"id":"239989000"},{"id":"247252410"},{"id":"247482000"},{"id":"???"},{"id":"215065000"},{"id":"???"},{"id":"304628000"},{"id":"227245460"},{"id":"227545850"},{"id":"228078900"},{"id":"???"},{"id":"232029964"},{"id":"???"},{"id":"247056100"},{"id":"227020210"},{"id":"211286290"},{"id":"247222320"},{"id":"247190200"},{"id":"???"},{"id":"255805844"},{"id":"319253000"},{"id":"211349960"},{"id":"247150870"},{"id":"???"},{"id":"247034200"},{"id":"???"},{"id":"227202000"},{"id":"2470027"},{"id":"255912850"},{"id":"247580000"},{"id":"227732750"},{"id":"???"},{"id":"247131600"},{"id":"247067730"},{"id":"247065500"},{"id":"247044790"},{"id":"227859220"},{"id":"247373200"},{"id":"319137400"},{"id":"???"},{"id":"311000104"},{"id":"247038220"},{"id":"247228650"},{"id":"205728930"},{"id":"227904440"},{"id":"538006783"},{"id":"2470050"},{"id":"247106900"},{"id":"247364270"},{"id":"247051600"},{"id":"???"},{"id":"???"},{"id":"248000749"},{"id":"247151070"},{"id":"???"},{"id":"???"},{"id":"227182000"},{"id":"247057100"},{"id":"247356500"},{"id":"235703000"},{"id":"247086200"},{"id":"???"},{"id":"232031099"},{"id":"227568170"},{"id":"247320400"},{"id":"227020300"},{"id":"247154490"},{"id":"215300000"},{"id":"???"},{"id":"???"},{"id":"247046800"},{"id":"???"},{"id":"???"},{"id":"269112430"},{"id":"256001151"},{"id":"2288242"},{"id":"228372900"},{"id":"???"},{"id":"235080934"},{"id":"248258000"},{"id":"???"},{"id":"277373000"},{"id":"247083700"},{"id":"247205000"},{"id":"227392140"},{"id":"???"},{"id":"247343200"},{"id":"???"},{"id":"247069980"},{"id":"269113270"},{"id":"203245426"},{"id":"211812560"},{"id":"538080084"},{"id":"235021357"},{"id":"227425840"},{"id":"247388600"},{"id":"247076570"},{"id":"???"},{"id":"247110700"},{"id":"247225210"},{"id":"???"},{"id":"256565000"},{"id":"247388800"},{"id":"228004550"},{"id":"215000824"},{"id":"218615000"},{"id":"247186700"},{"id":"247225880"},{"id":"???"},{"id":"???"},{"id":"???"},{"id":"225981613"},{"id":"227119730"},{"id":"227461070"},{"id":"211706890"},{"id":"247243600"},{"id":"???"},{"id":"2470042"},{"id":"???"},{"id":"247220130"},{"id":"???"},{"id":"???"},{"id":"???"},{"id":"228358800"},{"id":"227120990"},{"id":"247337300"},{"id":"247385700"},{"id":"235231000"},{"id":"235770000"},{"id":"227233780"},{"id":"247319500"},{"id":"???"},{"id":"310783000"},{"id":"???"},{"id":"247061700"},{"id":"256121000"},{"id":"2288236"},{"id":"???"},{"id":"249720000"},{"id":"247458000"},{"id":"229459000"},{"id":"218820000"},{"id":"???"},{"id":"247121200"},{"id":"247271100"},{"id":"111247501"},{"id":"???"},{"id":"319835000"},{"id":"247065580"},{"id":"227960860"},{"id":"???"},{"id":"247407000"},{"id":"247132400"},{"id":"247436000"},{"id":"2288241"},{"id":"247159350"},{"id":"???"},{"id":"247013400"},{"id":"228390600"},{"id":"229045000"},{"id":"254523000"},{"id":"356879000"},{"id":"???"},{"id":"???"},{"id":"310763000"},{"id":"???"},{"id":"319094900"},{"id":"???"},{"id":"232002797"},{"id":"???"},{"id":"???"},{"id":"211649470"},{"id":"247380050"},{"id":"247045600"},{"id":"247046600"},{"id":"227878310"},{"id":"???"},{"id":"???"},{"id":"???"},{"id":"211292200"},{"id":"227834780"},{"id":"???"},{"id":"247066220"},{"id":"227807140"},{"id":"247616000"},{"id":"???"},{"id":"???"},{"id":"2288231"},{"id":"310079000"},{"id":"???"},{"id":"215469000"},{"id":"235100652"},{"id":"???"},{"id":"227908470"},{"id":"247140560"},{"id":"577203000"},{"id":"???"},{"id":"247094000"},{"id":"538071072"},{"id":"???"},{"id":"269113200"},{"id":"???"},{"id":"229706000"},{"id":"235010730"},{"id":"247037120"},{"id":"247297200"},{"id":"314397000"},{"id":"227101320"},{"id":"247063240"},{"id":"227914470"},{"id":"247220050"},{"id":"227593840"},{"id":"227245000"},{"id":"247378700"},{"id":"227414980"},{"id":"578000800"},{"id":"247092950"},{"id":"247089500"},{"id":"???"},{"id":"227569780"},{"id":"???"},{"id":"2470038"},{"id":"236647000"},{"id":"247259540"},{"id":"247209100"},{"id":"211527530"},{"id":"???"},{"id":"354972000"},{"id":"???"},{"id":"247257320"},{"id":"???"},{"id":"247063450"},{"id":"2470052"},{"id":"227331290"},{"id":"247664000"}]}]
---8<---

![i](https://user-images.githubusercontent.com/236594/93627621-80166600-f9e5-11ea-861e-26d256512829.png)

**Comment by photopea** [comment]
Hi, I fixed it, thanks for reporting :)

**Comment by hbs** [comment]
Hi, the fixed version works on the image provided with the issue but fails with this new image.
![59-2](https://user-images.githubusercontent.com/236594/93759692-f647e200-fc0a-11ea-8bcf-c49ad2376202.png)

**Comment by photopea** [comment]
I fixed it again :)

**Comment by hbs** [comment]
I encountered yet another issue and fixed it by changing the 5 in 6! Any chance the unminified code lies somewhere? Does it come from pako?

**Comment by photopea** [comment]
The minified code is actually our library UZIP.js

The problem is, that when you see a compressed text of X bytes in "iTXt", it is not clear, how long is the decompressed text. Our decompressor, in order to be fast, tries to allocate a sufficiently long array just once, before the decompression.

Another method would be to start decompressing into an array of 1 Byte, and after each byte decoded, check, if we need to increase the size of an array.
