### ISSUE TITLE
Library JSON file needs to be updated

### ISSUE THREAD

**Issue by pxp1230** [photopea/UPNG.js#60]
2.1.0 is the version three years ago, the CDN server cannot automatically update to the current version

**Comment by photopea** [comment]
Hi, I am not familiar with CDN, could you make a pull request?

I use only my own JS code in my work, the json file was made by our fans.

**Comment by pxp1230** [comment]
I am not very clear about package.json, but I know the CDN server is synchronized with the [cdnjs](https://github.com/cdnjs/cdnjs) open source project repository.
cdnjs reads package.json of this repository, and then updates to here: https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/upng-js

**Comment by pxp1230** [comment]
Please draft a new release with Tag "v2.2.0" , then I guess CDN will be able to successfully update @photopea
