### ISSUE TITLE
upng.photopea.com - "Save all (zip)" button returns zip archive with size of 0 bytes

### ISSUE THREAD

**Issue by dranitski** [photopea/UPNG.js#66]
OS: Arch Linux, also reproduced on Windows 10
Google chrome Version 88.0.4324.182 (Official Build) (64-bit)
Firefox browser 87.0 (64-bit)

**Steps to reproduce:**
1. go to http://upng.photopea.com/
2. add one or more images 
3. click "Save all (zip)"
4. Receive zero-bytes size zip

**Comment by kasiaustas** [comment]
I have the same problem on Windows 10.  Browsers: Google chrome Version 89.0.4389.90 (Official Build) (64-bit), Firefox browser 86.0 (64-bit), Opera 74.0.3911.218 (64-bit)

**Comment by photopea** [comment]
I am very sorry, it is fixed now.
