### ISSUE TITLE
tabs / loop parameter

### ISSUE THREAD

**Issue by azgorov** [photopea/UPNG.js#68]
This is more of a question than issue.

from upng.js code I have this:

UPNG.encode = function(bufs, w, h, ps, dels, tabs, forbidPlte)

from docs UPNG.encode(imgs, w, h, cnum, [dels])

last 2 parameters are missing. 
Is there any reason for that. 

Using node 12 and trying to set loop count and from js code it is part of "tabs" pameter but this parameter is just ignored even if I add it at the end of encode function.

Best regards
Kalin

**Comment by photopea** [comment]
APNG animations are looped "infinitely" many times. There is no official way to change it.

You can give UPNG.encode() a fifth parameter: an object {loop:N}, to set the APNG to N loops. But I think people rarely want to specify a finite number of loops, so I prefer to keep the docs simple, without this.
