### ISSUE TITLE
APNG images at second index until <numimages> gets offset and gets wrong size

### ISSUE THREAD

**Issue by EtherTechDev** [photopea/UPNG.js#72]
When encoding buffers to APNG, I noticed that the second (and next-following) images are offset by 1 pixel left/top and has 1 pixel deducted from width and height. This seems like a bug, and it is caused by this code in UPNG.encode.framize function:

```
if(max==-1) mix=miy=max=may=0;
if(evenCrd) {  if((mix&1)==1)mix--;  if((miy&1)==1)miy--;  }
var sarea = (max-mix+1)*(may-miy+1);
if(sarea<tarea) {
	tarea = sarea;  tstp = it;
	nx = mi
}
```
I commented the code, and presto, the offset and w/h was correctly encoded for all images.
Perhaps removing the code will break something else (I didn't notice any problem though).
I used this excellent tool to inspect the APNG images: https://github.com/davidmz/apng-js.

**Comment by photopea** [comment]
I am not able to make it happen :(

How exactly are you using UPNG.js? If you use it according to the manual, "evenCrd" is never "true.

**Comment by EtherTechDev** [comment]
Closing due to not being a bug, but as it seems, a feature of APNG.
