### ISSUE TITLE
Reduce colors of raw ImageData without having to encode then decode a PNG

### ISSUE THREAD

**Issue by Merlin04** [photopea/UPNG.js#75]
In my application I have to use UPNG to compress a large quantity of images - specifically, given an `ImageData`, I need to reduce the colors to the provided value then output another `ImageData`. The way I'm currently doing this involves encoding the data as a PNG then decoding it again:
```ts
function transform(quality: number, image: ImageData): ImageData {
    const png = UPNG.encode([image.data.buffer], image.width, image.height, quality);
    const buf = UPNG.toRGBA8(UPNG.decode(png))[0];
    return new ImageData(new Uint8ClampedArray(buf), image.width, image.height);
}
```
However, from some testing it appears the decoding of the PNG on the second line of the function creates a significant performance bottleneck. Is it possible to avoid creating a PNG in the first place so I don't have to decode it, and just reduce the number of colors of the raw pixel data and output that?

**Comment by photopea** [comment]
Sure, check out our quantizer: UPNG.quantize(), it is described in the README.md

**Comment by photopea** [comment]
https://en.wikipedia.org/wiki/Color_quantization

**Comment by Merlin04** [comment]
That works great, thanks so much for the help (and for making such a great library!)
