### ISSUE TITLE
Make png image transparent from reference image

### ISSUE THREAD

**Issue by Lilja** [photopea/UPNG.js#77]
Hi! I could use some help.

This is the [image](https://www.smhi.se/pd/klimat/snow_depth/2223/sno221120.png), I'm trying to remove the white background. I can't simply just remove it in photoshop, because the source image from this website will generate daily. So I need an automated process to remove this background. I don't want to open up this image and remove the background so I thought I could make it work myself with some library.

I thought I came up with a good idea: take the land parts of the map and make it black. The rest should be transparent.
What I did, was to import it into photoshop, use the magic tool to remove the background from there and make the land black. I managed do [this](https://user-images.githubusercontent.com/6134511/202898889-693dd210-ab3b-443f-afd4-9371096f3099.png)

I opened up the file with this library and saw that my black and white img has just `0` and `255` in the buffer, perfect I thought. If the buf is 0, then that pixel is black and should use the contents of the source image for that pixel. If it's 255 then it needs to be fully transparent:
```javascript
const c = imgC.data; // current/source image
const t = imgT.data; // transparent image

const _new = new Uint8Array(imgC.data.length);

for (let i = 0; i<imgC.data.length; i++) {
  if (t[i] == 0) {
    _new[i] = c[i]
  } else {
    _new[i] = t[i];
  }
}
```

However, when this gets saved. It's just a black image. What am I doing wrong?

<details>

<summary>Code in its entirety</summary>

```javascript
const fs = require("fs");
var UPNG = require('upng-js');

const today = "/home/lilja/Downloads/smhi.png";
const transparent = "smhi-transparent.png";

const bufT = fs.readFileSync(transparent)
const imgT = UPNG.decode(bufT);
console.log(imgT);

const bufC = fs.readFileSync(today)
const imgC = UPNG.decode(bufC);
console.log(imgC);

const c = imgC.data;
const t = imgT.data;

const _new = new Uint8Array(imgC.data.length);

for (let i = 0; i<imgC.data.length; i++) {
  if (t[i] == 0) {
    _new[i] = c[i]
  } else {
    _new[i] = t[i];
  }
}

const ret = Buffer.from(UPNG.encode([_new], imgC.width, imgC.height,0))
const todayPrime = "./smhi-today.png";
fs.writeFileSync(todayPrime, ret);
```
</details>

**Comment by photopea** [comment]
Is your PNG paletted, or black and white, or RGB, or RGB + transparency? UPNG.decode(bufC).data can be 1 bit per pixel, 2, bits per pixel ... up to 64 bits per pixel.

I recommend to "normalize" it with UPNG.toRGBA8().

**Comment by Lilja** [comment]
> Is your PNG paletted, or black and white, or RGB, or RGB + transparency? 
I'm not sure I understand the question, but the source image has no transparency. My image has transparency + black pixels.

I tried to `normalize` it:

```
const cN = UPNG.toRGBA8(imgC);
const tN = UPNG.toRGBA8(imgT);

const _new = new Uint8Array(imgC.data.length);

for (let i = 0; i<cN; i++) {
  if (tN[i] == 0) {
    _new[i] = cN[i]
  } else {
    _new[i] = tN[i];
  }
}
```

I just get a transparent image from doing this.

**Comment by photopea** [comment]
const cN = UPNG.toRGBA8(imgC);
    for (let i = 0; i<cN; i++) {

The "cN" is not an integer, you can not compare "i<cN"

**Comment by photopea** [comment]
I would recommend you to read our docs properly: https://github.com/photopea/UPNG.js

**Comment by Lilja** [comment]
Thanks, noted after some more experimenting! I have seemed to solved it now, it took some trial and error.

Something I don't understand is the way to interact with the binary data:

```javascript
const width = 200;
const height = 200;
const size = width*height*4
const _new = new Uint8Array(size);

// Use 0,3,6,9, etc as base and write four times each loop.
for (let i = 0; i < height*width*4; i+=3) {
  _new[i] = 255;  // R?
  _new[i+1] = 0;  // G?
  _new[i+2] = 0;  // B?
  _new[i+3] = 255;// A?
}
const ret = Buffer.from(UPNG.encode([toArrayBuffer(_new)], width, height,0))
fs.writeFileSync("./test.png", ret);
```

In the for loop I think I am setting a red value of 255 with full transparency for every pixel. But the image is very strange:
![image](https://user-images.githubusercontent.com/6134511/202908743-7ed79f07-cde5-4020-ba63-4c4e863c5189.png)

It's like there are diagonal lines of red, instead the whole image is red.

I have to change the loop like this:
```javascript

for (let y = 0; y < height; y++) {
  for (let x = 0; x < width; x++) {
    const idx = (width*y+x) << 2;

    _new[idx] = 255;
    _new[idx+1] = 0;
    _new[idx+2] = 0;
    _new[idx+3] = 255;
  }
}
```

To make it completely solid.

Why is this nested for loop needed plus the index calculation with bit shifting to make a solid image?

**Comment by photopea** [comment]
You have a loop

    for (let i = 0; i < height*width*4; i+=3) {

it should be "i+=4", as there are four bytes per pixel.
