### ISSUE TITLE
How to tell if my pixel data is incorrect or my code is incorrect

### ISSUE THREAD

**Issue by velara3** [photopea/UPNG.js#78]
I have a library that extracts an image into pixel data. Is there example code that shows how to create a png file? 

```
var png = UPNG.encode([data], width, height, 0);
var buffer = Buffer.from(png);
var file = fs.writeFile("mypng.png", buffer); // images appear blank
```

Here is the data property: 
![image](https://user-images.githubusercontent.com/1084127/205716983-46a64c95-0e31-4a5e-ab14-bc7ba36469e2.png)

Exported image: 

<img width="382" alt="image" src="https://user-images.githubusercontent.com/1084127/205717330-1a091f93-7b42-4f88-8844-21d7c8f92fec.png">

Another example: 
<img width="457" alt="image" src="https://user-images.githubusercontent.com/1084127/205718519-eefac2d9-b86f-4fa9-a592-1187fe176ace.png">

The image is the correct size but also blank. 

If I remove the buffer line as shown in the code below I get an error from `writeFile`: 

```
var png = UPNG.encode([data], width, height, 0);
var file = fs.writeFile("mypng.png", png); 
```

> [TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of ArrayBuffer

**Comment by photopea** [comment]
what is "data" in your case? It should be an ArrayBuffer, not a Uint8Array. Could you start with a code in our README, and gradually modify it to what you need?
