### ISSUE TITLE
Why use UZIP only when the data length is greater than 10e6?

### ISSUE THREAD

**Issue by xuejianxianzun** [photopea/UPNG.js#79]
```js
var CMPR = (data.length>10e6 && UZIP!=null) ? UZIP : pako;
```
The file size of UZIP is much smaller than pako, so I want to use UZIP. Why is there such a condition? What if I always use UZIP?
Thank you！

**Comment by photopea** [comment]
I dont think UZIP always works better than pako. But you can rewrite it to var CMPR = UZIP.

**Comment by xuejianxianzun** [comment]
OK. In my test case, UZIP compressed 18% faster and 1% larger than pako. I have set to always use UZIP.
