### ISSUE TITLE
Check for optional UZIP dependency throws error (for large images)

### ISSUE THREAD

**Issue by 1j01** [photopea/UPNG.js#80]
This line throws `ReferenceError: UZIP is not defined`:
https://github.com/photopea/UPNG.js/blob/a4eafb5c77072162be3a6d968ac67d238a9d01ac/UPNG.js#L813

It should use `typeof` to safely check for the existence of a global, like so:
```js
	var CMPR = (data.length>10e6 && typeof UZIP!="undefined" && UZIP!=null) ? UZIP : pako;
```
The `UZIP!=null` part is still useful in case for example anyone was working around this by setting `window.UZIP = null;`

**Comment by photopea** [comment]
What if I check  

    window.UZIP!=null

that should work, right?

**Comment by 1j01** [comment]
Yes, that should be fine. The only difference would be in non-browser environments, which probably aren't supported.

**Comment by photopea** [comment]
Ok, I have uploaded a new version.
