### ISSUE TITLE
Image resizing

### ISSUE THREAD

**Issue by varun-raghavendra** [photopea/UPNG.js#85]
I see that Photopea.com allows us to resize an image based on the aspect ratio. However, I don't see this option in UPNG.js. Is there a smart way to use the UPNG.encode function so that it gives me the resized image? 

If not, how to resize an image the same way photopea does it?

**Comment by photopea** [comment]
Sorry, resizing images is not a part of this library.

When you convert an image to the "RGBA8 format", you can resize it somehow, and then, encode it back to a PNG.

If you want to resize it to a 2x2 pixel image, you can use the color of a top left pixel, top right, bottom left, bottom right. You should be able to find more information on resizing online (or find a JS library for resizing).
