### ISSUE TITLE
Output PNG file size not deterministic

### ISSUE THREAD

**Issue by varun-raghavendra** [photopea/UPNG.js#86]
I'm using UPNG.encode and I'm finding that it produces a different file size for 2 TIFF files with similar resolution. UTIF.decodeImage was done on both images to get RGBA arrays for both.

1. 
    - File - https://drive.google.com/file/d/19UJT0shqoXBnQ5QITt9k5u29XnPcVWRG/view?usp=drive_link. 
    - Output PNG size - 7 MB
2. 
    - File - https://drive.google.com/file/d/1R5DKQzAHlCmR0hkRAurn6ZkeONSQNgj-/view?usp=sharing, 
    - Output PNG size - 12MB

Why this disparity is there? 

Also, what is the zlib compression level used by UPNG.encode? Is there a way to tweak this?

**Comment by photopea** [comment]
The PNG image below is also 4K (3840x2160 pixels), but it is 0.001MB. It is 12 thousand times smaller than your PNG files, while having the same resolution.

Compression usually tries to describe the file with as few bytes as possible. A smaller file usually means that it contains "less information".

The upper limit is 3 Bytes per pixel. So a 4K PNG image is never bigger than 24.9 MB.

We dont use the Zlib library for the PNG compression.

**Comment by photopea** [comment]
![dwsample-tiff-4k](https://github.com/photopea/UPNG.js/assets/15955558/fca93b83-2c1a-4f57-9d4f-57865374f17c)
