### ISSUE TITLE
Support for more compression

### ISSUE THREAD

**Issue by varun-raghavendra** [photopea/UPNG.js#87]
Our use-case needs output PNG to be as compressed as possible. 

Is it possible to add compression options to UPNG.encode so that we can go for higher compression wherever needed? 

Is there any way the code can be modified to obtain higher compressions?

**Comment by photopea** [comment]
Could you prove that your image can be compressed to a smaller file than then one that the UPNG produces? Maybe if you let some compression run for several minutes, you could get a 1 - 2% smaller files, but I dont think it is worth it.

**Comment by varun-raghavendra** [comment]
No I cannot prove this. I did a mistake on my side which made me think there was an issue with the compression.
