### ISSUE TITLE
data array of wrong size

### ISSUE THREAD

**Issue by jonathanlurie** [photopea/UPNG.js#9]
Hi,
When I decode a png, the object given by UPNG has a wrong sized data array. I made a test image here (it is VERY small):  
![damier2_alpha](https://user-images.githubusercontent.com/1303310/29039566-c87165b4-7b79-11e7-8732-664d19e1862f.png)
and here is the screen capture from Chome's console:
![upng2](https://user-images.githubusercontent.com/1303310/29039592-e4e57280-7b79-11e7-8ab5-21c252925fbd.png)

The image is 12 pixels wide, 7 pixels high and has 4 components. This should give a data array of size 336 but instead gives a larger array (size 343).

I made other tests with other images and every time, the final array size is : `w*h*nc + h` instead of just `w*h*nc` , where `nc` is the number of components per pixel.  
I checked with other images and the issue is always here. The last `h` numbers of the array seem to be fake data, only 0, 1, 255,  and 254.

In case someone is interested, here is the workaround I use:  
```javascript
var pngData = png.decode( inputBuffer );
var ncpp = Math.round(pngData.data.length / (pngData.width*pngData.height) );
var croppedArray = new pngData.data.constructor( pngData.data.buffer, 0, pngData.width * pngData.height * ncpp);
```

Cheers.

Update: the method `UPNG.decode._inflate` just calls `pako.inflate`, and Pako seems to be responsible for the wrong size...

**Comment by photopea** [comment]
Hi Jonathan, I never noticed such thing. But it may be an issue of UPNG.js - maybe it gives Pako a little more data to decompress.

Anyway, if you want to be able to read any PNG in a four channel, 8 bits per channel format, without caring too much about details, I recommend using the `UPNG.toRGBA8(img)` afterwards. That should return a correct data of a correct size.

**Comment by photopea** [comment]
So I think I can close it now.

**Comment by jonathanlurie** [comment]
Ah ok, I'll try with `UPNG.toRGBA8(img)` then!
Thanks
